[config]
caching = true
version_check = true

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/hyprcolors.conf"

[templates.mango]
input_path = "./templates/mango-colors.conf"
output_path = "~/.config/mango/colors.conf"

[templates.discord]
input_path = "./templates/midnight-discord.css"
output_path = "~/.config/styles/discord/midnight.css"

[templates.yazi]
input_path = "./templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.fuzzel]
input_path = "./templates/fuzzel-colors.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.qtct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"
