[[sources]]
provider = "danbooru"
ids = [
  "7452256",
  "5931821",
  "8086139",
  "6714035",
  "5736719",
  "8771752",
  "8643096",
  "5670725",
  "8980627",
  "8959480",
  "8959682",
  "8945423",
  "8923646",
  "8852957",
  "8824359",
  "6073289",
  "5719657",
  "8958877",
  "8322508",
  "8285601",
  "8280034",
  "8255770",
  "8238034",
  "8233835",
  "8234888",
  "8233712",
  "7973468",
  "7275296",
  "8591266",
  "9005608",
  "8241196",
  "6531325",
  "8390291",
  "7680288",
  "5562482",
  "5628441",
  "6753700",
  "4285297",
  "3145837",
  "3144646",
  "4370850",
  "7575150",
  "7968030",
  "3035289",
  "6454574",
  "6554947",
  "6952501",
  "6546050",
  "7690649",
  "7171260",
  "7248761",
  "7861939",
  "7583054",
  "6991501",
  "5766191",
  "1867956",
  "3964469",
  "7041748",
  "7073390",
  "8149973",
  "7655511",
  "8463157",
  "5661586",
  "9057665",
  "5758657",
  "6607539",
  "7789954",
  "7652607",
  "7496228",
  "7429428",
  "6772355",
  "5579433",
  "5402131",
  "5039277",
  "4561580",
  "4832832",
  "9067689",
  "9072237",
  "6620972",
  "7873647",
  "5556929",
  "5555672",
  "5555676",
  "5555542",
  "5410017",
  "4878864",
  "8726475",
  "8412393",
  "6407203",
  "7472531",
  "6330817",
  "9044041",
  "6983927",
  "6045842",
  "6351551",
  "8989144",
  "8582191",
  "8464823",
  "8427823",
  "8391782",
  "8376174",
  "7181720",
  "7811494",
  "6327449",
  "5105737",
  "6490872",
  "7811485",
  "8553161",
  "9187380",
  "4345649",
  "7769103",
  "2031742",
  "5111613",
  "2332312",
  "4261224",
  "6747084",
  "8645525",
  "2183780",
  "5395555",
  "8306368",
  "9116980",
  "7714635",
  "7598783",
  "7557161",
  "7089622",
  "7240127",
  "5495546",
  "4982167",
  "4734562",
  "5727724",
  "6147541",
  "6456888",
  "5073049",
  "5640910",
  "7709624",
  "5661677",
  "5614777",
  "4785200",
  "6597069",
  "5680902",
  "6537693",
  "6842084",
  "6086092",
  "5662980",
  "5721257",
  "5806984",
  "6551763",
  "5862647",
  "6531325",
  "5205084",
  "8861659",
  "8712178",
  "9125417",
  "8713368",
  "8712601",
  "8713004",
  "8712634",
  "8688004",
  "9279499",
  "8714169",
  "8827425",
  "8732117",
  "8713730",
  "8718409",
  "8538483",
  "7372467",
  "9151461",
  "8557732",
  "8289013",
  "8377237",
  "7047547",
  "6981315",
  "8337467",
  "6928135",
  "7631102",
  "8680686",
  "8517559",
  "9468798",
  "9468970",
  "7818029",
  "5325474",
  "7272461",
  "5983945",
  "9351549",
  "5646066",
  "6241220",
  "6451042",
  "6094274",
  "6086092",
  "6746291",
  "5320317",
  "6885267",
  "6079266",
  "6887138",
  "9561442",
  "9561470",
  "6109256",
  "5682992",
  "5639034",
  "5202538",
  "9590836",
  "5736873",
  "7570570",
  "8429703",
  "7964366",
  "2768802",
  "6564075",
  "8447837",
  "7303513",
  "6752896",
  "7034838",
  "7296340",
  "9740351",
  "9766096",
  "9992382",
  "10014349",
  "9987754",
  "9998548",
  "9929440",
  "9881008",
  "9823185",
  "9695292",
  "9695278",
  "9245157",
  "10021400",
  "8582464",
  "9984695",
  "9247101",
  "7999989",
  "7521593",
  "7632124",
  "7853636",
  "7295580",
  "6545776",
  "7292131",
  "8301106",
  "7319066",
  "6851658",
  "8248381",
  "6411053",
  "6912978",
  "6980921",
  "7153319",
  "7091703",
  "6545492",
  "6852521",
  "6867369",
  "7328821",
  "9252226",
  "9252616",
  "4714099",
  "7712840",
  "8214060",
  "5134337",
  "4717183",
  "6944252",
  "8779016",
  "6105026",
  "8052846",
  "4755526",
  "7942708",
  "6186153",
  "8529560",
  "5003914",
  "9792468",
  "7602421",
  "10062302",
  "10057166",
  "10124155",
  "10227406",
  "10224733",
  "10254138",
  "6097216",
  "10248986",
  "10175654",
  "10148755",
  "6207390",
  "10484445",
  "9282696",
  "9249955",
  "9225895",
  "8960909",
  "8784694",
  "7481337",
  "7296238",
  "7203630",
  "7848839",
  "10015220",
  "9975940",
  "9163581",
  "8560900",
  "8582245",
  "7218356",
  "6512105",
]

[[providers]]
name = "pixiv"
url = "https://vx.maid.zone/proxy/i.pximg.net/img-original/img/%%ID%%"

[[sources]]
provider = "pixiv"
ids = [
  "2024/10/06/01/06/54/123071255_p0.png lingsha_feet",
  "2022/07/30/14/13/13/100089490_p0.jpg 100089490",
  "2023/02/05/01/25/29/105093461_p0.jpg 105093461",
  "2023/02/25/11/38/26/105507349_p1.jpg 105507349",
]

[[sources.overrides]]
identifier = "lingsha_feet"
append = false
characters = ["fuyuan_(honkai:_star_rail)", "lingsha_(honkai:_star_rail)"]
copyrights = ["honkai:_star_rail", "honkai_(series)"]
artists = ["atdan"]

[[sources.overrides]]
identifier = "100089490"
append = false
characters = ["fischl_(genshin_impact)", "mona_(genshin_impact)"]
copyrights = ["genshin_impact"]
artists = ["atdan"]

[[sources.overrides]]
identifier = "105093461"
append = false
characters = ["hu_tao_(genshin_impact)"]
copyrights = ["genshin_impact"]
artists = ["atdan"]

[[sources.overrides]]
identifier = "105507349"
append = false
characters = ["yelan_(genshin_impact)"]
copyrights = ["genshin_impact"]
artists = ["atdan"]

[filters]
artists = { list = [
  "atdan",
  "elodeas",
  "yoneyama_mai",
  "void_0",
  "morncolour",
  "yeurei",
  "meirong",
  "qianqianjie",
], inverted = true }

[preview_filters]
ratings = { list = ["e"], inverted = false }
ids = { list = [
  "7303513",
  "6752896",
  "9695292",
  "10021400",
  "8447837",
  "8726475",
  "8412393",
  "9044041",
  "7472531",
  "6407203",
  "6045842",
  "6351551",
  "5105737",
  "8553161",
  "9468798",
  "9468970",
  "5646066",
  "6241220",
  "8447837",
  "7296340",
  "8529560",
  "10175654",
], inverted = false }
providers = { list = ["urls", "pixiv"], inverted = false }
